### ISSUE TITLE
i18n tracking

### ISSUE THREAD

**Issue by GrumpyBear57** [LiveTL/website#14]
Translation strings added to Google Sheet: 
- [x] Navbar
- [x] Footer
- [x] DiscordServerLink
- [ ] Applications Page (Page is NYI)
- [x] Contact Page
- [x] FAQ Page
- [x] Home Page
- [ ] iOS Page (probably won't need to anyways since this is out of date and can probably be removed)
- [ ] Sign In Error Page
- [x] Translators Page

Translation strings implemented on site:
- [x] Navbar
- [x] Footer
- [x] DiscordServerLink
- [ ] Applications Page
- [ ] Contact Page
- [ ] FAQ Page
- [x] Home Page
- [ ] iOS Page
- [ ] Sign In Error Page
- [x] Translators Page

EDIT: Removed Privacy page as I don't feel it's necessary to have it translated. If someone wants to add support in the future, be my guest.
